### ISSUE TITLE
Figure out the naming structure for repos

### ISSUE THREAD

**Issue by planetoftheweb** [LinkedInLearning/prototype#1]
This is an issue where we can discuss the naming of our repositories.

**Comment by planetoftheweb** [comment]
Trying to remember everything from the meeting. We discussed a naming convention for the repositories which included.

1. Unique LinkedInLearning identifier
1. Original name of the github open source repo i.e. `bootstrap`
1. Identifier for the type of course this is. i.e. 'esst' for Essential Training
1. Course ID

So, the final name might be something like `lil-bootstrap-esst-1239238`

**Comment by mor10** [comment]
I think it should be this except not the "lil" part. This idea was totally just mine, nobody else had this idea. I am the original! 

`bootstrap-esst-12345938`

**Comment by tlarvenz** [comment]
Final-ish Version:
- Short name
- Identifier
- Milton ID

**Comment by planetoftheweb** [comment]
Sounds great. I'll close this issue and add this to the documentation.
