### ISSUE TITLE
Is split licensing voluntary when copyleft license is required?

### ISSUE THREAD

**Issue by siodice** [LinkedInLearning/prototype#19]
## Issue Overview

@mor10 
Regarding [https://github.com/LinkedInLearning/prototype/blob/master/DOCUMENTATION.md]

Under PREPARATION, 0. Producer + Instructor, the instructions say: "If a copyleft license such as GPL is required, CONSIDER split licensing:".  

Is it voluntary, or required, to do the split licensing, in this case?

**Comment by mor10** [comment]
Split licensing only kicks in when there is content that we must retain BSD or another license for. Most commonly it comes into play if the exercise files include media released under a different license. I would recommend course materials which include copyleft content adopt the license fully unless there is a specific need for split licensing.

**Comment by siodice** [comment]
That makes sense! Thanks @mor10 !
