### ISSUE TITLE
Suggestions for .gitignore file

### ISSUE THREAD

**Issue by planetoftheweb** [LinkedInLearning/prototype#6]
Add suggestions for the .gitignore file

**Comment by planetoftheweb** [comment]
I created a sample .gitignore file which lets you define which files or folders github should NOT track. For example the invisible files that MacOS creates and the node_modules folder that node.js creates. Feel free to suggest to and add to this.

**Comment by SaurabhAgarwal1243** [comment]
You can also add those files which your IDE adds on sometimes.

**Comment by planetoftheweb** [comment]
I'm going to close this issue. I think the gitignore is fine as is. People should customize this file if they think it's needed on a project by project basis.
