### ISSUE TITLE
Review Pull Request Template

### ISSUE THREAD

**Issue by planetoftheweb** [LinkedInLearning/prototype#7]
Started a Pull Request Template as suggested by Morten.

**Comment by mor10** [comment]
I think we need legal to add some sort of disclaimer to the pull request template along the lines of "by submitting code to this repo you grant us license to use that code in perpetuity in the universe for anything we want." Thoughts @siodice?

**Comment by siodice** [comment]
I agree. Let me talk with Legal today and get some language for this. I'll keep this open until I have the language to present here.

**Comment by planetoftheweb** [comment]
Sounds reasonable to me. 👍
