### ISSUE TITLE
Stock Assets

### ISSUE THREAD

**Issue by tlarvenz** [LinkedInLearning/prototype#9]
What should we be using for stock assets on the repo?

**Comment by tlarvenz** [comment]
Place holder images

or

LinkedIn homegrown asset packages 

or 

Download images from LinkedIn

**Comment by planetoftheweb** [comment]
For the time being, create a .gitignore file which prevents .gif, .jpg, .png, etc from being included with the course and link to the .zip. Also, work towards shooting a package that we can share on Github.
